@startuml CAPA DE DATOS
participant CAPA_NEGOCIO
participant CAPA_DATOS_ENTITY AS CDE
participant CAPA_DATOS_SQLSERVER AS CDSQL
participant SGBD
CAPA_NEGOCIO -> CDE: SOLICITA/ENVIA
note left
    SOLICITA/ENVIA INFORMACION 
    DE PROCESOS SEGUN SE REQUIERA
end note
alt LOGICA DE CAPA DATOS
CDE -> SGBD: SE CONECTA A SGBD
note right
    SE CONECTA A SGBD Y
    LEE/ESCRIBE/ACTUALIZA/ELIMINA(CRUD)
end note
SGBD -> CDE: RESPONDE LA PETICION CON LOS DATOS SOLICITADOS
note right
    RESPONDE EL RESULTADO
    DE LA EJECUCION DEL CRUD
end note
CDE -> CDE: TRANSFORMA LOS DATOS
note right
    TRANSFORMA LOS DATOS A
    UN MODELO DE OBJETO ADECUADO
    PARA LA CAPA DE NEGOCIO
end note
END
CDE -> CAPA_NEGOCIO: ENVIA LOS DATOS TRANSFORMADOS
@enduml