@startuml LOGICA DE LA N-CAPAS
participant CAPA_PRESENTACION
participant CAPA_NEGOCIO
participant CAPA_DATOS
participant SGBD
alt LOGICA DE PRESENTACION
CAPA_PRESENTACION -> CAPA_PRESENTACION: INTERFAZ SOLICITA A API_CONTROLLER
CAPA_PRESENTACION -> CAPA_NEGOCIO: EJECUTA PROCESO
note left
    EJECUTA PROCESO SEGUN 
    LO REQUIERA EL USUARIO
end note
CAPA_NEGOCIO -> CAPA_DATOS: SOLICITA/ENVIA
note left
    SOLICITA/ENVIA INFORMACION 
    DE PROCESOS SEGUN SE REQUIERA
end note
CAPA_DATOS -> SGBD: SE CONECTA A SGBD
note left
    SE CONECTA A SGBD Y
    LEE/ESCRIBE/ACTUALIZA/ELIMINA(CRUD)
end note
SGBD -> CAPA_DATOS: ENVIA RESPUESTA
note left
    RESPONDE EL RESULTADO
    DE LA EJECUCION DEL CRUD
end note
CAPA_DATOS -> CAPA_DATOS: TRANSFORMA LOS DATOS
note left
    TRANSFORMA LOS DATOS A
    UN MODELO DE OBJETO ADECUADO
    PARA LA CAPA DE NEGOCIO
end note
CAPA_DATOS -> CAPA_NEGOCIO: ENVIA LOS DATOS TRANSFORMADOS
CAPA_NEGOCIO -> CAPA_PRESENTACION: ENVIA LOS DATOS COMO RESPUESTA
note left
    MUESTRA LOS DATOS EN
    UNA SALIDA ADECUADA
    SEGUN LA SOLICITUD
end note
CAPA_PRESENTACION -> CAPA_PRESENTACION: API_CONTROLLER RESPONDE A LA INTERFAZ
@enduml